spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false

vite.mode=dev

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=core

# --- Flyway Migration ---
spring.flyway.enabled=true
spring.flyway.default-schema=core

# --- Spring Security ---
spring.security.user.name=admin
spring.security.user.password=admin

logging.file.name=logs/jobtracker.log
