spring.application.name=jobtracker
vite.mode=build

# spring.profiles.active=local

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:jobtracker_db}?currentSchema=core

# Flyway
spring.flyway.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:jobtracker_db}
spring.flyway.user=${SPRING_DATASOURCE_USERNAME:postgres}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD:postgres}